import type { PantryStockItem } from './types';

/**
 * Starter pantry so new installs aren’t empty — users can edit, add, or clear items anytime.
 */
export const DEFAULT_PANTRY_ITEMS: PantryStockItem[] = [
  {
    id: 'demo-onion',
    name: 'Onion',
    category: 'produce',
    quantity: 2,
    unitLabel: 'medium',
    lowStockAt: 1,
  },
  {
    id: 'demo-garlic',
    name: 'Garlic',
    category: 'produce',
    quantity: 1,
    unitLabel: '1 head',
    lowStockAt: 1,
  },
  {
    id: 'demo-tomatoes',
    name: 'Cherry Tomatoes',
    category: 'produce',
    quantity: 1,
    unitLabel: '400 g',
    lowStockAt: 1,
  },
  {
    id: 'demo-basil',
    name: 'Basil',
    category: 'produce',
    quantity: 1,
    unitLabel: '1 bunch',
    lowStockAt: 1,
  },
  {
    id: 'demo-eggs',
    name: 'Eggs',
    category: 'dairy',
    quantity: 6,
    unitLabel: '6 pack',
    lowStockAt: 3,
  },
  {
    id: 'demo-butter',
    name: 'Butter',
    category: 'dairy',
    quantity: 1,
    unitLabel: '250 g',
    lowStockAt: 1,
  },
  {
    id: 'demo-parmesan',
    name: 'Parmesan',
    category: 'dairy',
    quantity: 1,
    unitLabel: 'wedge',
    lowStockAt: 1,
  },
  {
    id: 'demo-chicken',
    name: 'Chicken Breast',
    category: 'meat_seafood',
    quantity: 2,
    unitLabel: 'fillets',
    lowStockAt: 1,
  },
  {
    id: 'demo-spaghetti',
    name: 'Spaghetti',
    category: 'dry_goods',
    quantity: 1,
    unitLabel: '500 g',
    lowStockAt: 1,
  },
  {
    id: 'demo-arborio',
    name: 'Arborio Rice',
    category: 'dry_goods',
    quantity: 1,
    unitLabel: '500 g',
    lowStockAt: 1,
  },
  {
    id: 'demo-oil',
    name: 'Olive Oil',
    category: 'dry_goods',
    quantity: 1,
    unitLabel: '750 ml',
    lowStockAt: 1,
  },
  {
    id: 'demo-stock',
    name: 'Vegetable Stock',
    category: 'dry_goods',
    quantity: 1,
    unitLabel: '1 L',
    lowStockAt: 1,
  },
  {
    id: 'demo-wine',
    name: 'White Wine',
    category: 'dry_goods',
    quantity: 1,
    unitLabel: 'bottle',
    lowStockAt: 1,
  },
  {
    id: 'demo-pepper',
    name: 'Red Pepper Flakes',
    category: 'spices',
    quantity: 1,
    unitLabel: 'small jar',
    lowStockAt: 1,
  },
  {
    id: 'demo-peas',
    name: 'Frozen Peas',
    category: 'frozen',
    quantity: 1,
    unitLabel: '400 g',
    lowStockAt: 1,
  },
];
